// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func MetricsTab(vm MetricsViewModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-8 animate-fadeIn\"><!-- Header --><div class=\"flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-gray-200 pb-5\"><div><h1 class=\"text-2xl font-bold tracking-tight text-gray-950\">System Telemetry Monitoring</h1><p class=\"mt-2 text-sm text-gray-500\">Real-time revision tracking, system throughput, and latency percentiles pulled from Cloud Monitoring.</p></div><div class=\"flex items-center gap-2 self-start md:self-center\"><span class=\"inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20\"><span class=\"h-1.5 w-1.5 mr-1.5 rounded-full bg-green-500 animate-pulse\"></span> Live Connection</span> <button onclick=\"window.location.reload()\" class=\"rounded-md bg-white px-3 py-1.5 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 transition\">Refresh</button></div></div><!-- KPI Grid --><div class=\"grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4\"><!-- Total Requests --><div class=\"relative overflow-hidden rounded-2xl bg-white px-6 pb-6 pt-5 border border-gray-200/80 shadow-sm hover:shadow-md transition-shadow duration-200\"><dt><div class=\"absolute rounded-lg bg-blue-50 p-2 text-blue-600\"><svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M7.5 14.25v2.25m3-4.5v4.5m3-6.75v6.75m3-9v9M6 20.25h12A2.25 2.25 0 0 0 20.25 18V6A2.25 2.25 0 0 0 18 3.75H6A2.25 2.25 0 0 0 3.75 6v12A2.25 2.25 0 0 0 6 20.25Z\"></path></svg></div><p class=\"ml-12 truncate text-sm font-medium text-gray-500\">Total Request Volume</p></dt><dd class=\"ml-12 flex items-baseline pb-0\"><p class=\"text-2xl font-semibold tracking-tight text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", vm.TotalRequests))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/dashboard/templates/metrics.templ`, Line: 39, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p><span class=\"ml-2 text-xs font-semibold text-gray-400\">last 24h</span></dd></div><!-- Peak Rate --><div class=\"relative overflow-hidden rounded-2xl bg-white px-6 pb-6 pt-5 border border-gray-200/80 shadow-sm hover:shadow-md transition-shadow duration-200\"><dt><div class=\"absolute rounded-lg bg-indigo-50 p-2 text-indigo-600\"><svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15.362 5.214A8.252 8.252 0 0 1 12 21 8.25 8.25 0 0 1 6.038 7.047 8.287 8.287 0 0 0 9 9.601a8.983 8.983 0 0 1 3.361-6.867 8.21 8.21 0 0 0 3 2.48Z\"></path> <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 18a3.75 3.75 0 0 0 .495-7.467 5.99 5.99 0 0 0-1.925 3.546 5.974 5.974 0 0 1-2.133-1A3.75 3.75 0 0 0 12 18Z\"></path></svg></div><p class=\"ml-12 truncate text-sm font-medium text-gray-500\">Peak Request Rate</p></dt><dd class=\"ml-12 flex items-baseline pb-0\"><p class=\"text-2xl font-semibold tracking-tight text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", vm.PeakRate))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/dashboard/templates/metrics.templ`, Line: 56, Col: 100}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p><span class=\"ml-2 text-xs font-semibold text-gray-400\">reqs/hour</span></dd></div><!-- P95 Latency --><div class=\"relative overflow-hidden rounded-2xl bg-white px-6 pb-6 pt-5 border border-gray-200/80 shadow-sm hover:shadow-md transition-shadow duration-200\"><dt><div class=\"absolute rounded-lg bg-orange-50 p-2 text-orange-600\"><svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z\"></path></svg></div><p class=\"ml-12 truncate text-sm font-medium text-gray-500\">P95 Response Time</p></dt><dd class=\"ml-12 flex items-baseline pb-0\"><p class=\"text-2xl font-semibold tracking-tight text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", vm.P95LatencyMs))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/dashboard/templates/metrics.templ`, Line: 72, Col: 104}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p><span class=\"ml-1 text-sm font-medium text-gray-500\">ms</span></dd></div><!-- Error Rate --><div class=\"relative overflow-hidden rounded-2xl bg-white px-6 pb-6 pt-5 border border-gray-200/80 shadow-sm hover:shadow-md transition-shadow duration-200\"><dt><div class=\"absolute rounded-lg bg-rose-50 p-2 text-rose-600\"><svg class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z\"></path></svg></div><p class=\"ml-12 truncate text-sm font-medium text-gray-500\">Routing Error Rate</p></dt><dd class=\"ml-12 flex items-baseline pb-0\"><p class=\"text-2xl font-semibold tracking-tight text-gray-900\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f%%", vm.ErrorRate))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/dashboard/templates/metrics.templ`, Line: 88, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></dd></div></div><!-- Charts Layout --><div class=\"grid grid-cols-1 gap-6 lg:grid-cols-2\"><!-- Volume Bar Chart --><div class=\"rounded-2xl border border-gray-200/80 bg-white p-6 shadow-sm\"><div class=\"flex items-center justify-between border-b border-gray-100 pb-4 mb-6\"><div><h3 class=\"text-base font-semibold text-gray-900\">Proxy Throughput Volume</h3><p class=\"text-xs text-gray-500 mt-0.5\">Hourly request counts over the last 24 hours</p></div><span class=\"inline-flex items-center rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700\">Bar Chart</span></div><div class=\"aspect-[16/7] w-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(vm.VolumeChartSVG).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><!-- Latency Line Chart --><div class=\"rounded-2xl border border-gray-200/80 bg-white p-6 shadow-sm\"><div class=\"flex items-center justify-between border-b border-gray-100 pb-4 mb-6\"><div><h3 class=\"text-base font-semibold text-gray-900\">Response Latency Percentiles</h3><p class=\"text-xs text-gray-500 mt-0.5\">Comparing Median (50th) and Peak (95th) latencies</p></div><div class=\"flex items-center gap-4\"><span class=\"inline-flex items-center gap-1.5 text-xs text-gray-500\"><span class=\"h-2 w-2 rounded-full bg-blue-500\"></span> Median</span> <span class=\"inline-flex items-center gap-1.5 text-xs text-gray-500\"><span class=\"h-2 w-2 rounded-full bg-orange-500\"></span> P95</span></div></div><div class=\"aspect-[16/7] w-full\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(vm.LatencyChartSVG).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
